# constants.py

"""Canonical constants & keys.

Keep this module as the stable public import surface for:
- session_state keys
- wizard step identifiers
- question/answer types
- schema versions

Focused constant groups live in private ``_constants`` modules to reduce merge
pressure. Application code should continue importing from this module.
"""

from __future__ import annotations

from typing import Final

from _constants.esco import (
    DEFAULT_ESCO_DATA_SOURCE_MODE,
    DEFAULT_ESCO_INDEX_STORAGE_PATH,
    DEFAULT_ESCO_RELEASE_LANE,
    DEFAULT_ESCO_SELECTED_VERSION,
    ESCO_ANCHOR_STATE_ANCHORED,
    ESCO_ANCHOR_STATE_ANCHORED_WITH_CONTEXT,
    ESCO_ANCHOR_STATE_DEGRADED,
    ESCO_ANCHOR_STATES,
    ESCO_API_MODES,
    ESCO_DATA_SOURCE_HYBRID,
    ESCO_DATA_SOURCE_LIVE_API,
    ESCO_DATA_SOURCE_MODES,
    ESCO_DATA_SOURCE_OFFLINE_INDEX,
    ESCO_QUESTION_SKILL_GROUP_CUSTOMER_CLIENT_INTERACTION,
    ESCO_QUESTION_SKILL_GROUP_DIGITAL_DATA_AI,
    ESCO_QUESTION_SKILL_GROUP_DOCUMENTATION_REPORTING,
    ESCO_QUESTION_SKILL_GROUP_DOMAIN_KNOWLEDGE,
    ESCO_QUESTION_SKILL_GROUP_IDS,
    ESCO_QUESTION_SKILL_GROUP_LANGUAGE_COMMUNICATION,
    ESCO_QUESTION_SKILL_GROUP_LEADERSHIP_COORDINATION,
    ESCO_QUESTION_SKILL_GROUP_PHYSICAL_MANUAL_CONTEXT,
    ESCO_QUESTION_SKILL_GROUP_REGULATION_SAFETY,
    ESCO_QUESTION_SKILL_GROUP_TOOLS_METHODS,
    ESCO_QUESTION_SKILL_GROUP_TRANSVERSAL_FIT,
    ESCO_RELEASE_LANE_PREVIEW,
    ESCO_RELEASE_LANE_SELECTED_VERSION,
    ESCO_RELEASE_LANE_STABLE,
    ESCO_RELEASE_LANES,
    ESCO_SECONDARY_ANCHOR_MAX,
    ESCO_SEMANTIC_EXPORT_MODE_ANCHORED,
    ESCO_SEMANTIC_EXPORT_MODE_DEGRADED,
    ESCO_SEMANTIC_EXPORT_MODES,
    OCCUPATION_QUESTION_MODULE_BASE,
    OCCUPATION_QUESTION_MODULE_ESCO_PREFIX,
    OCCUPATION_QUESTION_MODULE_ISCO1_PREFIX,
    OCCUPATION_QUESTION_MODULE_ISCO3_PREFIX,
    OCCUPATION_QUESTION_MODULE_ISCO4_PREFIX,
    OCCUPATION_QUESTION_MODULE_NACE_PREFIX,
    OCCUPATION_QUESTION_MODULE_REGULATED,
    OCCUPATION_QUESTION_MODULE_SKILL_GROUP_PREFIX,
    QUESTION_GROUP_DISPLAY_LABELS_DE,
)
from _constants.facts import (
    BEFORE_ARTIFACT_REQUIRED_FACT_KEYS,
    BEFORE_SUMMARY_REQUIRED_FACT_KEYS,
    FACT_REQUIREMENT_STAGE_DISPLAY_LABELS,
    FACT_SALARY_IMPACT_DISPLAY_LABELS,
    INTAKE_FACTS,
    SALARY_DRIVER_FACT_KEYS,
    SALARY_QUALITY_DRIVER_FACT_KEYS,
    WEBSITE_ENRICHABLE_FACT_KEYS,
    FactKey,
    FactPersistenceIntent,
    FactRequirementStage,
    FactResolutionStatus,
    FactSalaryImpact,
    FactSensitivity,
    FactSourceType,
    FactValueType,
    IntakeFactDef,
)
from _constants.questions import (
    AnswerType,
    JOBSPEC_ASSUMPTION_ANSWER_ID_PREFIX,
    JOBSPEC_NOTE_ROUTE_KEYWORDS,
    JOBSPEC_NOTE_ROUTE_STEP_KEYS,
    QUESTION_IMPACT_TARGET_BRIEF,
    QUESTION_IMPACT_TARGET_EXPORT,
    QUESTION_IMPACT_TARGET_INTERVIEW,
    QUESTION_IMPACT_TARGET_SALARY,
    QUESTION_IMPACT_TARGET_SKILLS,
    QUESTION_IMPACT_TARGETS,
    QUESTION_LIMIT_SCOPE_META_KEY,
)
from _constants.state_keys import SSKey
from _constants.summary import (
    SUMMARY_ACTIVE_ARTIFACT_IDS,
    SUMMARY_ARTIFACT_IDS,
    SUMMARY_ARTIFACT_LEGACY_ALIASES,
    SUMMARY_SESSION_KEY_LEGACY_ALIASES,
)
from _constants.ui import (
    UI_DETAILS_DEFAULT_BY_MODE_TEXT,
    UI_GLOBAL_DETAILS_TOGGLE_HELP,
    UI_GLOBAL_DETAILS_TOGGLE_LABEL,
    UI_LANGUAGE_COOKIE_KEY,
    UI_LANGUAGE_LAST_WIDGET_KEY,
    UI_LANGUAGE_QUERY_PARAM,
    UI_LANGUAGE_STORAGE_KEY,
    UI_LANGUAGE_VALUES,
    UI_LANGUAGE_WIDGET_KEY_PAGE,
    UI_LANGUAGE_WIDGET_KEY_SIDEBAR,
    UI_LANGUAGE_WIDGET_KEYS,
    UI_MODE_DEFAULT,
    UI_MODE_DISPLAY_LABELS,
    UI_MODE_HELP_TEXT,
    UI_MODE_PRIORITY_TIERS,
    UI_MODE_QUESTION_LIMIT_RATIOS,
    UI_MODE_STEP_QUESTION_CAPS,
    UI_MODE_VALUES,
    UI_PREFERENCE_ANSWER_MODE,
    UI_PREFERENCE_CONFIDENCE_THRESHOLD,
    UI_PREFERENCE_DETAILS_EXPANDED_DEFAULT,
    UI_PREFERENCE_ESCO_MATCHING_STRICTNESS,
    UI_PREFERENCE_INFORMATION_DEPTH,
    UI_PREFERENCE_PII_REDUCTION,
    UI_PREFERENCE_REGIONAL_FOCUS,
    UI_PREFERENCE_SHOW_SOURCES_DEFAULT,
    UI_PREFERENCE_STEP_COMPACT,
    UI_PREFERENCE_UI_LANGUAGE,
    UI_PREFERENCE_WIZARD_DESIGN,
    UI_STEP_COMPACT_TOGGLE_HELP,
    UI_STEP_COMPACT_TOGGLE_LABEL,
    UI_WIZARD_DESIGN_CLASSIC,
    UI_WIZARD_DESIGN_DEFAULT,
    UI_WIZARD_DESIGN_DISPLAY_LABELS,
    UI_WIZARD_DESIGN_FOCUS,
    UI_WIZARD_DESIGN_VALUES,
)
from _constants.usage import UsageEventType
from _constants.wizard import (
    COMPLETION_STATE_BADGE_TEXT,
    COMPLETION_STATE_COMPLETE,
    COMPLETION_STATE_NOT_STARTED,
    COMPLETION_STATE_PARTIAL,
    COMPLETION_STATE_PREFIX_TOKENS,
    COMPLETION_STATES,
    NON_INTAKE_STEP_KEYS,
    OPERATIONAL_WIZARD_STEP_KEYS,
    PRE_WIZARD_STEP_KEYS,
    PROGRESS_STEP_KEYS,
    STEPS,
    STEP_KEY_BENEFITS,
    STEP_KEY_COMPANY,
    STEP_KEY_INTERVIEW,
    STEP_KEY_INTRO,
    STEP_KEY_JOBSPEC_REVIEW,
    STEP_KEY_LANDING,
    STEP_KEY_ROLE_TASKS,
    STEP_KEY_SKILLS,
    STEP_KEY_SUMMARY,
    STEP_KEY_TEAM,
    STEP_SECTION_EXTRACTED_FROM_JOBSPEC,
    STEP_SECTION_IDS,
    STEP_SECTION_LABELS_DE,
    STEP_SECTION_OPEN_QUESTIONS,
    STEP_SECTION_REVIEW,
    STEP_SECTION_SALARY_FORECAST,
    STEP_SECTION_SLOT_NAMES,
    STEP_SECTION_SOURCE_COMPARISON,
    WIZARD_STEP_QUERY_PARAM,
    WizardStepDef,
)


APP_NAME: Final[str] = "Cognitive Staffing"
APP_TAGLINE: Final[str] = "AI-gestützte Kompetenz- und Matching-Workflows"
APP_TITLE: Final[str] = f"{APP_NAME} – Recruiting-Briefing"
DEFAULT_LANGUAGE: Final[str] = "de"
LLM_RESPONSE_CACHE_MAX_ENTRIES: Final[int] = 64

SOURCE_UPLOAD_MAX_BYTES: Final[int] = 10 * 1024 * 1024
SOURCE_UPLOAD_ALLOWED_EXTENSIONS: Final[tuple[str, ...]] = (
    ".pdf",
    ".docx",
    ".txt",
)
SOURCE_UPLOAD_MAX_BYTES_BY_EXTENSION: Final[dict[str, int]] = {
    ".pdf": SOURCE_UPLOAD_MAX_BYTES,
    ".docx": SOURCE_UPLOAD_MAX_BYTES,
    ".txt": SOURCE_UPLOAD_MAX_BYTES,
}
SOURCE_UPLOAD_FILE_SIGNATURES: Final[dict[str, tuple[bytes, ...]]] = {
    ".pdf": (b"%PDF-",),
    ".docx": (b"PK\x03\x04", b"PK\x05\x06", b"PK\x07\x08"),
    ".txt": (),
}
SOURCE_UPLOAD_TEXT_ENCODINGS: Final[tuple[str, ...]] = (
    "utf-8-sig",
    "utf-16",
    "cp1252",
    "latin-1",
)
SOURCE_UPLOAD_TEXT_MAX_CONTROL_CHAR_RATIO: Final[float] = 0.05
SUMMARY_LOGO_UPLOAD_MAX_BYTES: Final[int] = 2 * 1024 * 1024
SUMMARY_LOGO_UPLOAD_ALLOWED_MIME_TYPES: Final[tuple[str, ...]] = (
    "image/png",
    "image/jpeg",
)
SUMMARY_LOGO_UPLOAD_ALLOWED_EXTENSIONS: Final[tuple[str, ...]] = (
    ".png",
    ".jpg",
    ".jpeg",
)
SUMMARY_LOGO_UPLOAD_MIME_TYPE_BY_EXTENSION: Final[dict[str, str]] = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
}
JOBSPEC_SOURCE_MANUAL: Final[str] = "manual"
JOBSPEC_SOURCE_UPLOAD: Final[str] = "upload"
JOBSPEC_SOURCE_LEGACY_TEXT: Final[str] = "text"
JOBSPEC_SOURCE_VALUES: Final[tuple[str, str]] = (
    JOBSPEC_SOURCE_MANUAL,
    JOBSPEC_SOURCE_UPLOAD,
)

QUESTION_SCHEMA_VERSION: Final[str] = "2026-06-19"
VACANCY_SCHEMA_VERSION: Final[str] = "2026-06-24"
JOB_AD_SCHEMA_VERSION: Final[str] = "2026-06-10"
OCCUPATION_CONTEXT_SCHEMA_VERSION: Final[str] = "2026-06-03"
OCCUPATION_QUESTION_CONTEXT_SCHEMA_VERSION: Final[str] = "2026-06-11"
VACANCY_DRAFT_SCHEMA_VERSION: Final[str] = "2026-06-23"

# ---- Company website research canonical keys ----
WEBSITE_TOPIC_ABOUT: Final[str] = "about"
WEBSITE_TOPIC_IMPRINT: Final[str] = "imprint"
WEBSITE_TOPIC_VISION_MISSION: Final[str] = "vision_mission"

WEBSITE_RESEARCH_HOMEPAGE_URL: Final[str] = "homepage_url"
WEBSITE_RESEARCH_SECTIONS: Final[str] = "sections"
WEBSITE_RESEARCH_OPEN_QUESTION_MATCHES: Final[str] = "open_question_matches"

WEBSITE_SECTION_SOURCE_URL: Final[str] = "source_url"
WEBSITE_SECTION_SUMMARY: Final[str] = "summary"
WEBSITE_SECTION_FACTS: Final[str] = "facts"
WEBSITE_SECTION_FETCHED_AT: Final[str] = "fetched_at"

STALE_REDESIGN_SESSION_KEY_PREFIXES: Final[tuple[str, ...]] = (
    "cs.redesign.",
    "cs.summary.redesign.",
)

# Prefix used to generate stable Streamlit widget keys per question
WIDGET_KEY_PREFIX: Final[str] = "cs.q::"
