# ui_components.py
"""Reusable Streamlit UI components.

Compatibility facade for the focused ``ui_*`` modules. New code should import from
those focused modules directly when practical; existing callers can continue using
``ui_components`` during the transition.
"""

from __future__ import annotations

import streamlit as st

from job_extract_review_helpers import has_meaningful_value
from ui_badges import (
    ESCO_CONFIDENCE_BUCKETS,
    ESCO_EXPLAINABILITY_LABELS,
    ProvenanceBadge,
    build_provenance_badge,
    _normalize_esco_confidence,
    _normalize_esco_explainability_label,
    render_esco_explainability,
    render_provenance_badge,
)
from ui_esco_picker import (
    _build_esco_concept_id,
    _clean_esco_occupation_query,
    _extract_esco_suggestions,
    _infer_applied_provenance_categories,
    _normalize_esco_breadcrumb_nodes,
    _normalize_target_state_key,
    _render_esco_taxonomy_breadcrumb,
    render_esco_picker_card,
)
from ui_fact_review import (
    REVIEW_WIDGET_KEY_PREFIX,
    ReviewRenderContext,
    ReviewRenderMode,
    _can_render_inline_answer_inputs,
    _collect_incomplete_group_titles,
    _format_answer_for_review,
    _question_answer_provenance_label,
    _question_fact_evidence,
    _question_fact_key,
    _question_open_provenance_label,
    _resolve_review_render_mode,
    _truncate_for_review,
    build_step_review_payload,
    has_answered_question_with_keywords,
    render_recruiting_consistency_checklist,
    render_standard_step_review,
    render_step_review_card,
    resolve_standard_review_mode,
)
from ui_feedback import (
    render_error_banner,
    render_intake_process_animation,
    render_openai_error,
)
from ui_inputs import (
    PILLS_GRID_COLUMNS,
    QUESTION_ACQUISITION_COST_LABELS,
    QUESTION_ADJUSTMENT_LABELS,
    QUESTION_IMPACT_LABELS,
    QUESTION_PROVENANCE_SOURCE_LABELS,
    QUESTION_PROVENANCE_TEXT_MAX_CHARS,
    SECTION_PROVENANCE_TEXT_MAX_CHARS,
    QuestionInputResult,
    QuestionProvenanceDisplay,
    _build_question_provenance_display,
    _build_section_provenance_display,
    _can_render_question_step_form,
    _coerce_language_requirements,
    _coerce_multi_select_values,
    _coerce_number_value,
    _coerce_single_select_value,
    _compact_question_adjustment_label,
    _compact_question_source_label,
    _dedupe_labels,
    _ensure_step_group_state,
    _extract_other_text,
    _fallback_question_why,
    _format_question_provenance_caption,
    _get_global_details_expanded_default,
    _get_step_compact_preference,
    _get_step_group_rules,
    _get_ui_preferences,
    _group_questions,
    _infer_default_value,
    _inject_esco_single_select_pills_css,
    _is_group_open,
    _is_language_requirement_question,
    _is_percentage_number_question,
    _join_compact_question_provenance_labels,
    _join_provenance_labels,
    _load_question_flow_provenance_payload,
    _matches_keywords,
    _parse_scale_bounds,
    _persist_question_answer,
    _persist_question_inputs,
    _provenance_string_list,
    _question_adjustment_labels,
    _question_count_label,
    _question_count_verb,
    _question_group_title,
    _question_has_source_uris,
    _question_hidden_scope_caption,
    _question_impact_labels,
    _question_option_entries,
    _question_source_labels,
    _question_step_form_key,
    _question_widget_help,
    _render_grouped_question_inputs,
    _render_html_block,
    _render_language_requirement_question,
    _render_number_question,
    _render_question,
    _render_question_provenance,
    _render_questions_two_columns,
    _render_section_provenance,
    _rerun_after_question_form_submit,
    _resolve_number_constraints,
    _safe_question_provenance_text,
    _set_session_flag_true,
    _set_step_compact_preference,
    _set_step_group_open_state,
    _sort_questions_for_progressive_disclosure,
    _split_core_and_detail_questions,
    _strip_other_from_multiselect,
    inject_pills_grid_css,
    render_next_best_question_coach,
    render_question_step,
)
from ui_job_extract import (
    _compact_value_rows,
    _field_evidence_column_config,
    _join_compact_location,
    _render_compact_extract_lists,
    _render_compact_job_extract_overview,
    _render_compact_list_section,
    _render_compact_list_table,
    _render_compact_value_section,
    _render_contacts_editor,
    _render_editable_job_extract,
    _render_field_evidence_caption,
    _render_list_editor,
    _render_note_block,
    _render_question_limits_editor,
    _render_recruitment_steps_editor,
    _render_salary_editor,
    _suggested_question_limit,
    render_job_extract_overview,
)
from ui_requirement_board import (
    _build_requirement_table_rows,
    _is_high_importance,
    _normalize_requirement_label,
    _render_requirement_selection_table,
    _truncate_requirement_label,
    render_compare_adopt_intro,
    render_compact_requirement_board,
)
from ui_source_pills import (
    SourcePillColumn,
    SourcePillColumnFooter,
    SourcePillColumnWithFooter,
    SourcePillSelectionResult,
    _source_pill_provenance_caption,
    dedupe_source_pill_labels,
    normalize_source_pill_label,
    render_multi_select_pills,
    render_source_pill_selection,
)
from ui_summary_artifacts import (
    _first_boolean_query,
    _has_visible_boolean_queries,
    _render_boolean_code_card,
    _visible_boolean_channels,
    render_boolean_risks,
    render_boolean_search_pack,
    render_boolean_supporting_terms,
    render_boolean_usage_notes,
    render_brief,
    render_employment_contract_draft,
    render_interview_prep_fach,
    render_interview_prep_hr,
)
