"""Service facade for guarded homepage enrichment.

The implementation remains in ``homepage_research`` to preserve the existing
security, cache, and compatibility contract while UI code migrates to this
service layer.
"""

from __future__ import annotations

from homepage_research import (
    ALLOWED_CONTENT_TYPE_PREFIXES,
    HOMEPAGE_FETCH_ALLOWED_DOMAINS_ENV,
    HOMEPAGE_FETCH_MAX_BYTES,
    HOMEPAGE_FETCH_MAX_REDIRECTS,
    HOMEPAGE_FETCH_NEGATIVE_CACHE_TTL_SECONDS,
    HOMEPAGE_FETCH_TIMEOUT_SEC,
    PAGE_KEYWORDS,
    USER_AGENT,
    WEBSITE_TOPIC_LABELS,
    CompanyWebsiteResearchResult,
    HomepageFetchError,
    HomepageFetchResult,
    HomepageResearchInvalidUrlError,
    build_company_website_research,
    build_open_question_match_options,
    build_website_fact_candidates,
    clear_fetch_cache,
    contains_noise,
    derive_insights_from_open_questions,
    derive_topic_facts,
    extract_essential_sentences,
    extract_imprint_facts,
    extract_links,
    fetch_url_text,
    fetch_url_text_result,
    find_candidate_url,
    find_candidate_urls,
    is_useful_sentence,
    normalize_company_website_research_payload,
    normalize_research_facts,
    normalize_url,
    sentence_score,
    strip_html,
)

__all__ = [
    "ALLOWED_CONTENT_TYPE_PREFIXES",
    "HOMEPAGE_FETCH_ALLOWED_DOMAINS_ENV",
    "HOMEPAGE_FETCH_MAX_BYTES",
    "HOMEPAGE_FETCH_MAX_REDIRECTS",
    "HOMEPAGE_FETCH_NEGATIVE_CACHE_TTL_SECONDS",
    "HOMEPAGE_FETCH_TIMEOUT_SEC",
    "PAGE_KEYWORDS",
    "USER_AGENT",
    "WEBSITE_TOPIC_LABELS",
    "CompanyWebsiteResearchResult",
    "HomepageFetchError",
    "HomepageFetchResult",
    "HomepageResearchInvalidUrlError",
    "build_company_website_research",
    "build_open_question_match_options",
    "build_website_fact_candidates",
    "clear_fetch_cache",
    "contains_noise",
    "derive_insights_from_open_questions",
    "derive_topic_facts",
    "extract_essential_sentences",
    "extract_imprint_facts",
    "extract_links",
    "fetch_url_text",
    "fetch_url_text_result",
    "find_candidate_url",
    "find_candidate_urls",
    "is_useful_sentence",
    "normalize_company_website_research_payload",
    "normalize_research_facts",
    "normalize_url",
    "sentence_score",
    "strip_html",
]
